version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: your-app-name
    container_name: your-container-name
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://username:password@db:5432/dbname
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: your-db-container-name
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
